repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
    - id: isort

-   repo: https://github.com/PyCQA/autoflake
    rev: v1.6.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports']

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    -   id: codespell
        args:
        - --skip=".git"
        - --ignore-words-list=pimacs
